# 2018 consts 
# Base scenario values

GENDER_PAY_GAP_WORKERS <- 22.65
DISP_INCOME_GAP_WORKERS <- 10.27
DISP_INCOME_GAP_ALL <- 15.08

IN_WORK_POVERTY_RATE <- 7.38

# Absolute poverty line
ABSOLUTE_POVERTY_LINE <- 215.44

# Absolute poverty rates
ABSOLUTE_POVERTY_RATE <- 0.64

# Household absolute poverty rates

# Single man
ABSOLUTE_POVERTY_RATE_SINGLE_MAN <- 6.42

# Single woman
ABSOLUTE_POVERTY_RATE_SINGLE_WOMAN <- 2.16

# Childless couple <65
ABSOLUTE_POVERTY_RATE_CHILDLESS_COUPLE <- 0.63

# Single parent
ABSOLUTE_POVERTY_RATE_SINGLE_PARENT <- 0.19

# Couple with 1 child
ABSOLUTE_POVERTY_RATE_COUPLE_ONE_CHILD <- 0

# Couple with 2 children
ABSOLUTE_POVERTY_RATE_COUPLE_TWO_CHILDREN <- 0

# Couple with 3+ children
ABSOLUTE_POVERTY_RATE_COUPLE_MANY_CHILDREN <- 0


# RELATIVE poverty rates
RELATIVE_POVERTY_RATE <- 17.93

# Household relative poverty rates

# Single man
RELATIVE_POVERTY_RATE_SINGLE_MAN <- 33.62

# Single woman
RELATIVE_POVERTY_RATE_SINGLE_WOMAN <- 22.68

# Childless couple <65
RELATIVE_POVERTY_RATE_CHILDLESS_COUPLE <- 9.31

# Single parent
RELATIVE_POVERTY_RATE_SINGLE_PARENT <- 30.12

# Couple with 1 child
RELATIVE_POVERTY_RATE_COUPLE_ONE_CHILD <- 7.35

# Couple with 2 children
RELATIVE_POVERTY_RATE_COUPLE_TWO_CHILDREN <- 9.74

# Couple with 3+ children
RELATIVE_POVERTY_RATE_COUPLE_MANY_CHILDREN <- 7.35

# Taxes and benefits
SOCIAL_TAX_PAID <- 319729148
INCOME_TAX_PAID <- 127477769
SUBSISTENCE_BENEFIT_RECEIVED <- 3218140
ALL_BENEFITS_RECEIVED <- 235355798
PRIVATE_PAY_EXPENSE <- 982599388
PUBLIC_PAY_EXPENSE <- 120781916