# 2017 consts 
# Base scenario values

GENDER_PAY_GAP_WORKERS <- 24.26
DISP_INCOME_GAP_WORKERS <- 13.19
DISP_INCOME_GAP_ALL <- 17.19

IN_WORK_POVERTY_RATE <- 7.38

# Absolute poverty line
ABSOLUTE_POVERTY_LINE <- 207.23

# Absolute poverty rates
ABSOLUTE_POVERTY_RATE <- 0.94

# Household absolute poverty rates

# Single man
ABSOLUTE_POVERTY_RATE_SINGLE_MAN <- 7.96

# Single woman
ABSOLUTE_POVERTY_RATE_SINGLE_WOMAN <- 2.83

# Childless couple <65
ABSOLUTE_POVERTY_RATE_CHILDLESS_COUPLE <- 1.27

# Single parent
ABSOLUTE_POVERTY_RATE_SINGLE_PARENT <- 0

# Couple with 1 child
ABSOLUTE_POVERTY_RATE_COUPLE_ONE_CHILD <- 0.64

# Couple with 2 children
ABSOLUTE_POVERTY_RATE_COUPLE_TWO_CHILDREN <- 0

# Couple with 3+ children
ABSOLUTE_POVERTY_RATE_COUPLE_MANY_CHILDREN <- 0


# RELATIVE poverty rates
RELATIVE_POVERTY_RATE <- 16.94

# Household relative poverty rates

# Single man
RELATIVE_POVERTY_RATE_SINGLE_MAN <- 33.87

# Single woman
RELATIVE_POVERTY_RATE_SINGLE_WOMAN <- 24.5

# Childless couple <65
RELATIVE_POVERTY_RATE_CHILDLESS_COUPLE <- 10.01

# Single parent
RELATIVE_POVERTY_RATE_SINGLE_PARENT <- 20.14

# Couple with 1 child
RELATIVE_POVERTY_RATE_COUPLE_ONE_CHILD <- 11.96

# Couple with 2 children
RELATIVE_POVERTY_RATE_COUPLE_TWO_CHILDREN <- 10.42

# Couple with 3+ children
RELATIVE_POVERTY_RATE_COUPLE_MANY_CHILDREN <- 12.01

# Taxes and benefits
SOCIAL_TAX_PAID <- 287708239
INCOME_TAX_PAID <- 128939420
SUBSISTENCE_BENEFIT_RECEIVED <- 3378058
ALL_BENEFITS_RECEIVED <- 220847821