# 2020 consts 
# Base scenario values

GENDER_PAY_GAP_WORKERS <- 22.46
DISP_INCOME_GAP_WORKERS <- 10.59
DISP_INCOME_GAP_ALL <- 15.15

IN_WORK_POVERTY_RATE <- 6.96

# Absolute poverty line
ABSOLUTE_POVERTY_LINE <- 220.36

# Absolute poverty rates
ABSOLUTE_POVERTY_RATE <- 0.45

# Household absolute poverty rates

# Single man
ABSOLUTE_POVERTY_RATE_SINGLE_MAN <- 5.47

# Single woman
ABSOLUTE_POVERTY_RATE_SINGLE_WOMAN <- 1.35

# Childless couple <65
ABSOLUTE_POVERTY_RATE_CHILDLESS_COUPLE <- 0.26

# Single parent
ABSOLUTE_POVERTY_RATE_SINGLE_PARENT <- 0

# Couple with 1 child
ABSOLUTE_POVERTY_RATE_COUPLE_ONE_CHILD <- 0

# Couple with 2 children
ABSOLUTE_POVERTY_RATE_COUPLE_TWO_CHILDREN <- 0

# Couple with 3+ children
ABSOLUTE_POVERTY_RATE_COUPLE_MANY_CHILDREN <- 0


# RELATIVE poverty rates
RELATIVE_POVERTY_RATE <- 17.08

# Household relative poverty rates

# Single man
RELATIVE_POVERTY_RATE_SINGLE_MAN <- 32.99

# Single woman
RELATIVE_POVERTY_RATE_SINGLE_WOMAN <- 21.29

# Childless couple <65
RELATIVE_POVERTY_RATE_CHILDLESS_COUPLE <- 9.21

# Single parent
RELATIVE_POVERTY_RATE_SINGLE_PARENT <- 29.34

# Couple with 1 child
RELATIVE_POVERTY_RATE_COUPLE_ONE_CHILD <- 7.3

# Couple with 2 children
RELATIVE_POVERTY_RATE_COUPLE_TWO_CHILDREN <- 9.65

# Couple with 3+ children
RELATIVE_POVERTY_RATE_COUPLE_MANY_CHILDREN <- 7.99

# Taxes and benefits
SOCIAL_TAX_PAID <- 363071993
INCOME_TAX_PAID <- 157689226
SUBSISTENCE_BENEFIT_RECEIVED <- 3179955
ALL_BENEFITS_RECEIVED <- 269953701
PRIVATE_PAY_EXPENSE <- 1115257655
PUBLIC_PAY_EXPENSE <- 136865711