# 2019 consts 
# Base scenario values

GENDER_PAY_GAP_WORKERS <- 22.56
DISP_INCOME_GAP_WORKERS <- 10.35
DISP_INCOME_GAP_ALL <- 15.09

IN_WORK_POVERTY_RATE <- 6.99

# Absolute poverty line
ABSOLUTE_POVERTY_LINE <- 221.36

# Absolute poverty rates
ABSOLUTE_POVERTY_RATE <- 0.48

# Household absolute poverty rates

# Single man
ABSOLUTE_POVERTY_RATE_SINGLE_MAN <- 6.03

# Single woman
ABSOLUTE_POVERTY_RATE_SINGLE_WOMAN <- 1.32

# Childless couple <65
ABSOLUTE_POVERTY_RATE_CHILDLESS_COUPLE <- 0.26

# Single parent
ABSOLUTE_POVERTY_RATE_SINGLE_PARENT <- 0

# Couple with 1 child
ABSOLUTE_POVERTY_RATE_COUPLE_ONE_CHILD <- 0

# Couple with 2 children
ABSOLUTE_POVERTY_RATE_COUPLE_TWO_CHILDREN <- 0

# Couple with 3+ children
ABSOLUTE_POVERTY_RATE_COUPLE_MANY_CHILDREN <- 0


# RELATIVE poverty rates
RELATIVE_POVERTY_RATE <- 17.37

# Household relative poverty rates

# Single man
RELATIVE_POVERTY_RATE_SINGLE_MAN <- 32.75

# Single woman
RELATIVE_POVERTY_RATE_SINGLE_WOMAN <- 21.29

# Childless couple <65
RELATIVE_POVERTY_RATE_CHILDLESS_COUPLE <- 9.19

# Single parent
RELATIVE_POVERTY_RATE_SINGLE_PARENT <- 30.12

# Couple with 1 child
RELATIVE_POVERTY_RATE_COUPLE_ONE_CHILD <- 7.34

# Couple with 2 children
RELATIVE_POVERTY_RATE_COUPLE_TWO_CHILDREN <- 9.52

# Couple with 3+ children
RELATIVE_POVERTY_RATE_COUPLE_MANY_CHILDREN <- 7.99

# Taxes and benefits
SOCIAL_TAX_PAID <- 343517908
INCOME_TAX_PAID <- 143950142
SUBSISTENCE_BENEFIT_RECEIVED <- 3366617
ALL_BENEFITS_RECEIVED <- 253117521
PRIVATE_PAY_EXPENSE <- 1056212783
PUBLIC_PAY_EXPENSE <- 129730680	